language: haskell

notifications:
  irc:
    channels:
      - "irc.freenode.org#hnn"
    skip_join: true
    template:
      - "\x0313hnn\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"

script:
  - cabal install --only-dependencies && cabal configure && cabal build

before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - sudo apt-get update -qq
  - cabal update
  - sudo apt-get install -qq libgsl0-dev gsl-bin libblas3 libblas-dev liblapack-dev liblapack3

install:
  - cabal install --only-dependencies